branches:
  only:
  - master

dist: focal

language: python
python:
    - 3.8
env:
- TOXENV=django22
- TOXENV=django30

sudo: false

services:
    - xvfb

cache: pip
before_install:
    - "export DISPLAY=:99.0"
    - export DJANGO_SETTINGS_MODULE=registrar.settings.test

install:
    - pip install -U pip wheel
    - make requirements
script:
    - make validate_translations
    - make validate
    - make static
after_success:
    - pip install -U codecov
    - codecov
